name: Sync ReactFlux Content to Main

on:
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout YOUR repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        ref: main
        repository: ivancarlosti/miniflixreader
        persist-credentials: true

    - name: Show initial state
      run: |
        echo "=== INITIAL STATE ==="
        echo "Working directory:"
        pwd
        echo "Files before sync:"
        ls -la
        echo "Git status before:"
        git status

    - name: Download and sync content
      run: |
        mkdir -p temp
        cd temp
        git clone --branch gh-pages --depth 1 https://github.com/electh/ReactFlux.git
        echo "=== SOURCE FILES ==="
        ls -la ReactFlux/
        echo "=== SYNCING ==="
        rsync -av --exclude='.github' --progress ReactFlux/ ../
        cd ..
        echo "=== RESULT AFTER SYNC ==="
        ls -la

    - name: Verify changes
      run: |
        echo "=== CHANGES TO BE COMMITTED ==="
        git add .
        git status
        git diff --cached --stat
        if [ -z "$(git status --porcelain)" ]; then
          echo "No changes detected!"
          exit 1
        fi

    - name: Commit changes
      run: |
        git config --global user.email "ivan@ivancarlos.com.br"
        git config --global user.name "ivancarlosti"
        git commit -m "Sync ReactFlux content [automated]"
        git show --stat

    - name: Push changes
      run: |
        git remote -v
        git push origin main
        echo "=== PUSH VERIFICATION ==="
        git ls-remote --heads origin
