name: Sync ReactFlux gh-pages content
on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:

jobs:
  sync-content:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git config --global --add safe.directory /github/workspace

      - name: Download and sync gh-pages content
        run: |
          # Download the gh-pages branch as zip
          echo "Downloading gh-pages content..."
          wget -q https://github.com/electh/ReactFlux/archive/refs/heads/gh-pages.zip -O gh-pages.zip
          
          # Extract zip
          unzip -q gh-pages.zip
          rm gh-pages.zip

          # Backup files to preserve
          mkdir -p preserve-temp
          [ -f "CNAME" ] && cp CNAME preserve-temp/
          [ -f "README.md" ] && cp README.md preserve-temp/
          [ -f "LICENSE" ] && cp LICENSE preserve-temp/

          # Clear existing content except protected files/folders
          find . -mindepth 1 \
            ! -name '.git' \
            ! -name '.github' \
            ! -name 'CNAME' \
            ! -name 'README.md' \
            ! -name 'LICENSE' \
            -exec rm -rf {} +

          # Move content from the ReactFlux-gh-pages directory
          if [ -d "ReactFlux-gh-pages" ]; then
            echo "Moving content from ReactFlux-gh-pages directory..."
            shopt -s dotglob
            mv ReactFlux-gh-pages/* ./
            rm -rf ReactFlux-gh-pages
          else
            echo "Error: ReactFlux-gh-pages directory not found"
            echo "Current directory contents:"
            ls -la
            exit 1
          fi

          # Restore preserved files
          [ -f "preserve-temp/CNAME" ] && mv preserve-temp/CNAME ./
          [ -f "preserve-temp/README.md" ] && mv preserve-temp/README.md ./
          [ -f "preserve-temp/LICENSE" ] && mv preserve-temp/LICENSE ./
          rm -rf preserve-temp

      - name: Commit and push changes
        run: |
          git add -A
          if ! git diff-index --quiet HEAD; then
            git commit -m "Auto-sync with ReactFlux gh-pages content"
            git push
          else
            echo "No changes to commit"
          fi
