name: Sync ReactFlux gh-pages content
on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:

jobs:
  sync-content:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git config --global --add safe.directory /github/workspace

      - name: Download and verify gh-pages content
        run: |
          # Create fresh temp directory
          TEMP_DIR=$(mktemp -d)
          echo "Created temp directory: $TEMP_DIR"
          
          # Download the zip file with verbose output
          echo "Downloading gh-pages.zip..."
          wget --show-progress -O "$TEMP_DIR/gh-pages.zip" https://github.com/electh/ReactFlux/archive/refs/heads/gh-pages.zip
          
          # Verify download
          echo "Download verification:"
          ls -lh "$TEMP_DIR/gh-pages.zip"
          file "$TEMP_DIR/gh-pages.zip"
          unzip -l "$TEMP_DIR/gh-pages.zip" | head -10
          
          # Extract to temp directory
          echo "Extracting..."
          unzip -q "$TEMP_DIR/gh-pages.zip" -d "$TEMP_DIR"
          rm "$TEMP_DIR/gh-pages.zip"
          
          # Verify extraction
          echo "Extracted content:"
          find "$TEMP_DIR" -maxdepth 2 -type d -print
          
          # Copy to sync-temp for examination
          mkdir -p sync-temp
          cp -r "$TEMP_DIR"/* sync-temp/
          echo "Copied to sync-temp for debugging:"
          ls -la sync-temp
          
          # Move content to workspace root
          if [ -d "$TEMP_DIR/ReactFlux-gh-pages" ]; then
            echo "Moving content to workspace root..."
            shopt -s dotglob
            mv "$TEMP_DIR/ReactFlux-gh-pages"/* ./
            rm -rf "$TEMP_DIR"
          else
            echo "Error: Could not find ReactFlux-gh-pages in extracted content"
            echo "Temp directory contents:"
            find "$TEMP_DIR" -type d -print
            exit 1
          fi

      - name: Backup and clean workspace
        run: |
          # Backup files to preserve
          mkdir -p preserve-temp
          [ -f "CNAME" ] && cp CNAME preserve-temp/
          [ -f "README.md" ] && cp README.md preserve-temp/
          [ -f "LICENSE" ] && cp LICENSE preserve-temp/
          
          # Clear existing content except protected files/folders
          find . -mindepth 1 \
            ! -name '.git' \
            ! -name '.github' \
            ! -name 'CNAME' \
            ! -name 'README.md' \
            ! -name 'LICENSE' \
            ! -name 'sync-temp' \
            -exec rm -rf {} +

      - name: Restore preserved files
        run: |
          [ -f "preserve-temp/CNAME" ] && mv preserve-temp/CNAME ./
          [ -f "preserve-temp/README.md" ] && mv preserve-temp/README.md ./
          [ -f "preserve-temp/LICENSE" ] && mv preserve-temp/LICENSE ./
          rm -rf preserve-temp

      - name: Commit and push changes
        run: |
          git add -A
          if ! git diff-index --quiet HEAD; then
            git commit -m "Auto-sync with ReactFlux gh-pages content"
            git push
          else
            echo "No changes to commit"
          fi
