name: Sync ReactFlux gh-pages content
on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:

jobs:
  sync-content:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git config --global --add safe.directory /github/workspace

      - name: Download and sync gh-pages content
        run: |
          # Create a temporary working directory
          WORK_DIR=$(mktemp -d)
          echo "Working directory: $WORK_DIR"
          
          # Download and extract the gh-pages content
          cd $WORK_DIR
          wget -q https://github.com/electh/ReactFlux/archive/refs/heads/gh-pages.zip -O gh-pages.zip
          unzip -q gh-pages.zip
          rm gh-pages.zip
          
          # Verify content was downloaded
          echo "Downloaded content:"
          ls -la $WORK_DIR/ReactFlux-gh-pages/
          
          # Return to repository root
          cd $GITHUB_WORKSPACE
          
          # Backup files to preserve
          mkdir -p preserve-temp
          [ -f "CNAME" ] && cp CNAME preserve-temp/
          [ -f "README.md" ] && cp README.md preserve-temp/
          [ -f "LICENSE" ] && cp LICENSE preserve-temp/

          # Clear existing content except protected files/folders
          find . -mindepth 1 \
            ! -name '.git' \
            ! -name '.github' \
            ! -name 'CNAME' \
            ! -name 'README.md' \
            ! -name 'LICENSE' \
            -exec rm -rf {} +

          # Move new content from temporary directory
          if [ -d "$WORK_DIR/ReactFlux-gh-pages" ]; then
            echo "Moving content from $WORK_DIR/ReactFlux-gh-pages"
            shopt -s dotglob
            mv $WORK_DIR/ReactFlux-gh-pages/* ./
            rm -rf $WORK_DIR
          else
            echo "Error: Downloaded content not found in $WORK_DIR"
            echo "Contents of $WORK_DIR:"
            ls -la $WORK_DIR
            exit 1
          fi

          # Restore preserved files
          [ -f "preserve-temp/CNAME" ] && mv preserve-temp/CNAME ./
          [ -f "preserve-temp/README.md" ] && mv preserve-temp/README.md ./
          [ -f "preserve-temp/LICENSE" ] && mv preserve-temp/LICENSE ./
          rm -rf preserve-temp

      - name: Commit and push changes
        run: |
          git add -A
          if ! git diff-index --quiet HEAD; then
            git commit -m "Auto-sync with ReactFlux gh-pages content"
            git push
          else
            echo "No changes to commit"
          fi
