name: Sync ReactFlux gh-pages content
on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:

jobs:
  sync-content:
    runs-on: ubuntu-latest
    steps:
      # First checkout with proper permissions
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: true

      # Immediately verify we're in a git repo
      - name: Verify Git context
        run: |
          echo "Current directory: $(pwd)"
          ls -la
          git rev-parse --git-dir
          git config --global --add safe.directory "$GITHUB_WORKSPACE"

      # Download and process content in isolated temp dir
      - name: Download gh-pages content
        run: |
          TEMP_DIR=$(mktemp -d)
          cd $TEMP_DIR
          wget -q https://github.com/electh/ReactFlux/archive/refs/heads/gh-pages.zip
          unzip -q gh-pages.zip
          rm gh-pages.zip
          echo "Downloaded content:"
          find . -maxdepth 2 -type d
          cd $GITHUB_WORKSPACE

      # Backup protected files
      - name: Backup configuration
        run: |
          mkdir -p .sync-backup
          cp -f CNAME README.md LICENSE .sync-backup/ || true
          echo "Backup contents:"
          ls -la .sync-backup

      # Clear existing content
      - name: Clean workspace
        run: |
          find . -mindepth 1 \
            ! -name '.git' \
            ! -name '.github' \
            ! -name '.sync-backup' \
            -exec rm -rf {} +

      # Move new content
      - name: Move new content
        run: |
          shopt -s dotglob
          mv $TEMP_DIR/ReactFlux-gh-pages/* ./
          rm -rf $TEMP_DIR
          mv .sync-backup/* ./
          rm -rf .sync-backup

      # Final commit with explicit git context
      - name: Commit changes
        run: |
          cd $GITHUB_WORKSPACE
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add -A
          if ! git diff-index --quiet HEAD; then
            git commit -m "Auto-sync with ReactFlux gh-pages content"
            git push
          else
            echo "No changes to commit"
          fi
