name: Sync ReactFlux Content to Main

on:
  workflow_dispatch:  # Remove schedule until testing is complete

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout YOUR repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        ref: main
        repository: ivancarlosti/miniflixreader  # Explicitly specify YOUR repo
        persist-credentials: true

    - name: Download ReactFlux content
      run: |
        mkdir -p temp
        cd temp
        git clone --branch gh-pages --depth 1 https://github.com/electh/ReactFlux.git
        echo "Copying files (excluding .github)..."
        rsync -av --exclude='.github' ReactFlux/ ../
        cd ..
        rm -rf temp

    - name: Commit changes
      run: |
        git config --global user.email "ivan@ivancarlos.com.br"
        git config --global user.name "ivancarlosti"
        git add .
        
        if [ -n "$(git status --porcelain)" ]; then
          git commit -m "Sync ReactFlux content [automated]"
          echo "Changes committed"
        else
          echo "No changes to commit"
          exit 0
        fi

    - name: Push to YOUR repository
      run: |
        # Explicitly push to YOUR repo using GITHUB_TOKEN
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/ivancarlosti/miniflixreader.git
        git push origin main
        echo "Push successful to ivancarlosti/miniflixreader"
