name: Sync ReactFlux Content

on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        ref: gh-pages  # Try to checkout gh-pages branch
        persist-credentials: true

    - name: Create gh-pages branch if it doesn't exist
      run: |
        if ! git show-ref --quiet refs/heads/gh-pages; then
          echo "Creating gh-pages branch..."
          git checkout --orphan gh-pages
          git rm -rf .
          echo "Initial commit" > README.md
          git add README.md
          git commit -m "Initialize gh-pages branch"
        else
          echo "gh-pages branch already exists"
        fi

    - name: Download ReactFlux tree
      run: |
        mkdir -p temp
        cd temp
        git clone --branch gh-pages --depth 1 https://github.com/electh/ReactFlux.git
        rsync -av --exclude='.github' --exclude='CNAME' --exclude='README.md' --exclude='LICENSE' ReactFlux/ ../
        cd ..
        rm -rf temp

    - name: Commit and push changes
      run: |
        git config --global user.email "ivan@ivancarlos.com.br"
        git config --global user.name "ivancarlosti"
        git add .
        
        if git diff --quiet && git diff --cached --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Sync ReactFlux content"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          git push origin gh-pages
        fi
