name: Sync ReactFlux gh-pages content
on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:

jobs:
  sync-content:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download ReactFlux gh-pages content
        run: |
          # Clone the source repo
          if ! git clone --depth 1 --branch gh-pages https://github.com/electh/ReactFlux.git reactflux-temp; then
            echo "Failed to clone repository"
            exit 1
          fi

          # Backup files to preserve
          mkdir -p preserve-temp
          [ -f "CNAME" ] && cp CNAME preserve-temp/
          [ -f "README.md" ] && cp README.md preserve-temp/
          [ -f "LICENSE" ] && cp LICENSE preserve-temp/
          
          # Remove existing content except protected files/folders
          find . -mindepth 1 \
            ! -name '.git' \
            ! -name '.github' \
            ! -name 'CNAME' \
            ! -name 'README.md' \
            ! -name 'LICENSE' \
            -exec rm -rf {} +

          # Move content if any exists
          if [ -d "reactflux-temp" ]; then
            shopt -s dotglob nullglob
            mv reactflux-temp/* ./ || echo "No files to move"
            # Handle .github separately if it exists
            if [ -d "reactflux-temp/.github" ]; then
              mv reactflux-temp/.github ./
            fi
            rm -rf reactflux-temp
          fi
          
          # Restore preserved files
          [ -f "preserve-temp/CNAME" ] && mv preserve-temp/CNAME ./
          [ -f "preserve-temp/README.md" ] && mv preserve-temp/README.md ./
          [ -f "preserve-temp/LICENSE" ] && mv preserve-temp/LICENSE ./
          rm -rf preserve-temp

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git config --global --add safe.directory /github/workspace

      - name: Commit and push changes
        run: |
          git add -A
          git diff-index --quiet HEAD || git commit -m "Auto-sync with ReactFlux gh-pages branch"
          git push
