name: Sync ReactFlux gh-pages content
on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:

jobs:
  sync-content:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git config --global --add safe.directory /github/workspace
          git config --global --add safe.directory /github/workspace/sync-temp

      - name: Download and extract gh-pages content
        run: |
          # Create sync-temp directory
          mkdir -p sync-temp
          cd sync-temp
          
          # Download and extract
          wget -q https://github.com/electh/ReactFlux/archive/refs/heads/gh-pages.zip -O gh-pages.zip
          unzip -q gh-pages.zip
          rm gh-pages.zip
          
          # Debug: Show extracted structure
          echo "Extracted content structure:"
          find . -type d -print
          
          # Move back to root
          cd ..

      - name: Verify Git repository
        run: |
          echo "Current directory: $(pwd)"
          echo "Git status:"
          git status
          echo "Directory contents:"
          ls -la

      - name: Sync content
        run: |
          # Backup files to preserve
          mkdir -p preserve-temp
          [ -f "CNAME" ] && cp CNAME preserve-temp/
          [ -f "README.md" ] && cp README.md preserve-temp/
          [ -f "LICENSE" ] && cp LICENSE preserve-temp/

          # Clear existing content except protected files/folders
          find . -mindepth 1 \
            ! -name '.git' \
            ! -name '.github' \
            ! -name 'CNAME' \
            ! -name 'README.md' \
            ! -name 'LICENSE' \
            ! -name 'sync-temp' \
            -exec rm -rf {} +

          # Move content from sync-temp
          if [ -d "sync-temp/ReactFlux-gh-pages" ]; then
            echo "Moving content from sync-temp..."
            shopt -s dotglob
            mv sync-temp/ReactFlux-gh-pages/* ./
            rm -rf sync-temp
          else
            echo "Error: Content not found in sync-temp"
            echo "sync-temp contents:"
            ls -la sync-temp
            exit 1
          fi

          # Restore preserved files
          [ -f "preserve-temp/CNAME" ] && mv preserve-temp/CNAME ./
          [ -f "preserve-temp/README.md" ] && mv preserve-temp/README.md ./
          [ -f "preserve-temp/LICENSE" ] && mv preserve-temp/LICENSE ./
          rm -rf preserve-temp

      - name: Commit and push changes
        run: |
          git add -A
          if ! git diff-index --quiet HEAD; then
            git commit -m "Auto-sync with ReactFlux gh-pages content"
            git push
          else
            echo "No changes to commit"
          fi
