name: Sync ReactFlux gh-pages content
on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:

jobs:
  sync-content:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Verify Git repository
        run: |
          echo "Current directory: $(pwd)"
          git status
          echo "Directory contents:"
          ls -la

      - name: Download and process gh-pages content
        run: |
          # Create isolated working directory
          WORK_DIR=$(mktemp -d)
          echo "Work directory: $WORK_DIR"
          
          # Download and extract gh-pages
          cd $WORK_DIR
          wget -q https://github.com/electh/ReactFlux/archive/refs/heads/gh-pages.zip
          unzip -q gh-pages.zip
          rm gh-pages.zip
          
          # Verify downloaded content
          echo "Downloaded content structure:"
          find . -type d
          
          # Return to repository
          cd $GITHUB_WORKSPACE
          
          # Backup protected files
          mkdir -p .backup
          [ -f "CNAME" ] && cp CNAME .backup/
          [ -f "README.md" ] && cp README.md .backup/
          [ -f "LICENSE" ] && cp LICENSE .backup/
          
          # Clear existing content (preserve .git, .github, and backup)
          find . -mindepth 1 \
            ! -name '.git' \
            ! -name '.github' \
            ! -name '.backup' \
            ! -name 'CNAME' \
            ! -name 'README.md' \
            ! -name 'LICENSE' \
            -exec rm -rf {} +

          # Move new content
          if [ -d "$WORK_DIR/ReactFlux-gh-pages" ]; then
            shopt -s dotglob
            mv $WORK_DIR/ReactFlux-gh-pages/* ./
            rm -rf $WORK_DIR
          else
            echo "Error: Downloaded content structure:"
            find $WORK_DIR -type d
            exit 1
          fi
          
          # Restore protected files
          [ -f ".backup/CNAME" ] && mv .backup/CNAME ./
          [ -f ".backup/README.md" ] && mv .backup/README.md ./
          [ -f ".backup/LICENSE" ] && mv .backup/LICENSE ./
          rm -rf .backup

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git config --global --add safe.directory $GITHUB_WORKSPACE
          git add -A
          if ! git diff-index --quiet HEAD; then
            git commit -m "Auto-sync with ReactFlux gh-pages content"
            git push
          else
            echo "No changes to commit"
          fi
