name: Sync ReactFlux Content to Main

on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout main branch
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        ref: main  # Explicitly checkout main branch
        persist-credentials: true

    - name: Download ReactFlux tree
      run: |
        mkdir -p temp
        cd temp
        git clone --branch gh-pages --depth 1 https://github.com/electh/ReactFlux.git
        rsync -av --exclude='.github' --exclude='CNAME' --exclude='README.md' --exclude='LICENSE' ReactFlux/ ../
        cd ..
        rm -rf temp

    - name: Commit and push changes to main
      run: |
        git config --global user.email "ivan@ivancarlos.com.br"
        git config --global user.name "ivancarlosti"
        git add .
        
        if git diff --quiet && git diff --cached --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Sync ReactFlux content [automated]"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          git pull --rebase origin main  # Ensure we're up to date
          git push origin main
        fi
