name: Sync ReactFlux Content to Main

on:
  workflow_dispatch:  # Temporarily remove schedule for testing

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout main branch
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        ref: main
        persist-credentials: true

    - name: Show initial state
      run: |
        echo "Current files:"
        ls -la
        echo "Git status:"
        git status

    - name: Download ReactFlux content
      run: |
        mkdir -p temp
        cd temp
        git clone --branch gh-pages --depth 1 https://github.com/electh/ReactFlux.git
        echo "ReactFlux files:"
        ls -la ReactFlux/
        rsync -av --exclude='.github' ReactFlux/ ../
        cd ..
        rm -rf temp
        echo "Files after sync:"
        ls -la

    - name: Commit changes
      run: |
        git config --global user.email "ivan@ivancarlos.com.br"
        git config --global user.name "ivancarlosti"
        git add .
        git status
        git diff --cached --stat
        if ! git diff --quiet || ! git diff --cached --quiet; then
          git commit -m "Sync ReactFlux content [automated]"
          git show --stat  # Show what's being committed
        else
          echo "No changes to commit"
        fi

    - name: Push changes
      run: |
        git remote -v
        git push origin main -v
        echo "Push complete. Latest commits:"
        git log --oneline -n 3
