name: Sync ReactFlux Content

on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Download ReactFlux tree
      run: |
        mkdir -p temp
        cd temp
        git clone --branch gh-pages --depth 1 https://github.com/electh/ReactFlux.git
        rsync -av --exclude='.github' --exclude='CNAME' --exclude='README.md' --exclude='LICENSE' ReactFlux/ ../
        cd ..
        rm -rf temp

    - name: Commit changes
      run: |
        git config --global user.email "ivan@ivancarlos.com.br"
        git config --global user.name "ivancarlosti"
        git add .
        git commit -m "Sync ReactFlux content"
        git push
