name: Sync ReactFlux gh-pages content
on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:

jobs:
  sync-content:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download ReactFlux gh-pages content
        run: |
          git clone --depth 1 --branch gh-pages https://github.com/electh/ReactFlux.git reactflux-temp
          
          mkdir -p preserve-temp
          [ -f "CNAME" ] && cp CNAME preserve-temp/
          [ -f "README.md" ] && cp README.md preserve-temp/
          [ -f "LICENSE" ] && cp LICENSE preserve-temp/
          
          find . -maxdepth 1 \
            ! -name '.git' \
            ! -name '.github' \
            ! -name 'CNAME' \
            ! -name 'README.md' \
            ! -name 'LICENSE' \
            -exec rm -rf {} +
          
          mv reactflux-temp/{.,}* ./
          rm -rf reactflux-temp
          
          [ -f "preserve-temp/CNAME" ] && mv preserve-temp/CNAME ./
          [ -f "preserve-temp/README.md" ] && mv preserve-temp/README.md ./
          [ -f "preserve-temp/LICENSE" ] && mv preserve-temp/LICENSE ./
          rm -rf preserve-temp

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add -A
          git diff-index --quiet HEAD || git commit -m "Auto-sync with ReactFlux gh-pages branch"
          git push
