name: Sync ReactFlux Content to Main

on:
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout YOUR repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        ref: main
        repository: ivancarlosti/miniflixreader
        # This ensures fresh clone of YOUR repo:
        clean: true  
        persist-credentials: true

    - name: Reset Git remote (CRITICAL FIX)
      run: |
        git remote remove origin || true
        git remote add origin https://github.com/ivancarlosti/miniflixreader.git
        git remote -v  # Verify remote

    - name: Download ReactFlux content
      run: |
        mkdir -p temp
        cd temp
        git clone --branch gh-pages --depth 1 https://github.com/electh/ReactFlux.git
        echo "=== Files in ReactFlux ==="
        ls -la ReactFlux/
        echo "=== Copying files ==="
        rsync -av \
          --exclude='.github' \
          --exclude='.git' \
          ReactFlux/ ../
        cd ..
        echo "=== Files after copy ==="
        ls -la

    - name: Commit changes
      run: |
        git config --global user.email "ivan@ivancarlos.com.br"
        git config --global user.name "ivancarlosti"
        git add .
        
        if [ -n "$(git status --porcelain)" ]; then
          git commit -m "Sync ReactFlux content [automated]"
          echo "=== Commit details ==="
          git show --stat
        else
          echo "No changes to commit"
          exit 0
        fi

    - name: Push to YOUR repository (AUTH FIX)
      run: |
        # Use GitHub's native token authentication
        git push \
          https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/ivancarlosti/miniflixreader.git \
          HEAD:main
        echo "=== Push successful ==="
        echo "Verify at: https://github.com/ivancarlosti/miniflixreader/tree/main"
